module.exports = {
    SEND: 0,
    SIGNATURE: 1,
    DELEGATE: 2,
    VOTE: 3,
    USERNAME: 4,
    FOLLOW: 5,
    MULTI: 6,
    DAPP: 7,
    IN_TRANSFER: 8,
    OUT_TRANSFER: 9,
    ASSETS: 10,
    TRANSFERS: 11,
    BURN: 12,
    OTHER: 13,
    LOCK_HEIGHT: 14,
    MINER_IP: 15,
    DO_DAPP: 16,
    ISSUERS: 17,
    DAPP_TRANSFER: 18
};